# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet           # Official Go vet
    - errcheck        # Ensure errors are handled
    - staticcheck     # Advanced static analysis (includes gosimple)
    - unused          # Unused code detection
    - ineffassign     # Unused assignments
    - revive          # Style linter (golint replacement)
    - bodyclose       # HTTP response body closure
    - noctx           # HTTP requests with context
    - gocritic        # Additional checks
    - depguard        # Import boundary enforcement
    - forbidigo       # Enforce output abstraction usage
    - gosec           # Security vulnerability detection
    - errorlint       # Error wrapping correctness (Go 1.13+)
    - misspell        # Spelling errors in comments/strings
    - unconvert       # Unnecessary type conversions
    - nilerr          # Nil error return detection
    - usetesting      # Modern testing package patterns
    - varnamelen      # Variable name length by scope
    - nolintlint      # Ensure nolint directives are strict
    - wrapcheck       # Ensure external errors are wrapped
    - rowserrcheck    # Ensure DB rows errors are checked
    - sqlclosecheck   # Ensure SQL resources are closed
    - copyloopvar     # Catch unsafe loop var captures
    - durationcheck   # Invalid duration math
    - bidichk         # Dangerous bidi sequences
    - errname         # Error naming conventions
    - nilnil          # Disallow nil,nil and invalid nil returns
    - nilnesserr      # Mismatched nil checks and returns
    - fatcontext      # Context created in loops/closures
    - predeclared     # Shadowing predeclared identifiers
    - usestdlibvars   # Prefer stdlib constants/vars
    - wastedassign    # Detect wasted assignments
    - dupl            # Duplicate code blocks
    - godot           # Require period at end of comments
    - whitespace      # Remove unnecessary blank lines
    - wsl_v5          # Enforce whitespace style
    - thelper         # Enforce t.Helper in test helpers
    - tparallel       # Detect unsafe t.Parallel usage
  settings:
    govet:
      enable:
        - shadow        # Variable shadowing detection
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        # CLI output functions - errors are non-recoverable
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*github.com/fatih/color.Color).Fprint
        - (*github.com/fatih/color.Color).Fprintf
        - (*github.com/fatih/color.Color).Fprintln
        # HTTP response body close - Body returns io.ReadCloser
        - (io.ReadCloser).Close
        - (io.Closer).Close
    revive:
      severity: error
      rules:
        - name: exported
          disabled: false
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    depguard:
      rules:
        internal_no_cmd_import:
          files:
            - internal/**/*.go
          deny:
            - pkg: github.com/musher-dev/mush/cmd/mush
              desc: internal packages must not import cmd/mush
        platform_no_presentation:
          files:
            - internal/client/**/*.go
            - internal/auth/**/*.go
            - internal/config/**/*.go
            - internal/update/**/*.go
            - internal/harness/provider.go
            - internal/worker/**/*.go
            - internal/errors/**/*.go
            - internal/buildinfo/**/*.go
            - internal/terminal/**/*.go
            - internal/paths/**/*.go
            - internal/ansi/**/*.go
            - internal/observability/**/*.go
            - internal/transcript/**/*.go
            - internal/testutil/**/*.go
          deny:
            - pkg: github.com/musher-dev/mush/internal/output
              desc: platform/core packages must not depend on output
            - pkg: github.com/musher-dev/mush/internal/prompt
              desc: platform/core packages must not depend on prompt
        testutil_no_production:
          files:
            - "!**/*_test.go"
          deny:
            - pkg: github.com/musher-dev/mush/internal/testutil
              desc: testutil is for tests only — must not be imported by production code
        doctor_no_output:
          files:
            - internal/doctor/**/*.go
          deny:
            - pkg: github.com/musher-dev/mush/internal/output
              desc: doctor package must remain output-agnostic
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^fmt\.Print(ln)?$
          msg: "use output.Writer.Print() or Println() instead"
        - pattern: ^fmt\.Printf$
          msg: "use output.Writer.Print() instead"
        - pattern: ^log\.(Print|Fatal|Panic)(ln|f)?$
          msg: "use output.Writer instead of log package"
    gosec:
      excludes:
        - G104        # Redundant with errcheck linter
        - G115        # Safe fd conversions in terminal handling
        - G117        # AccessToken field name is required by API schema
        - G602        # Indexing guarded by length checks; false-positive in state machine
        - G703        # Paths are generated internally and validated
        - G704        # Base URL is trusted configuration, not user input
      config:
        global:
          nosec: true
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    misspell:
      locale: "US"
    usetesting:
      os-create-temp: true
      os-mkdir-temp: true
      os-setenv: true
      os-temp-dir: true
      os-chdir: true
      context-background: true
      context-todo: true
    varnamelen:
      min-name-length: 3
      check-receiver: false
      check-return: false
      check-type-param: false
      ignore-names:
        - i
        - j
        - k
        - v
        - w
        - t
        - ok
        - id
        - ip
        - db
        - tx
        - wg
        - mu
        - ch
        - fs
        - io
        - c
        - p
        - r
        - h
        - s
        - b
        - n
        - f
        - ev
        - sc
        - bw
        - gz
      ignore-decls:
        - c *cobra.Command
        - c *client.Client
        - c *client.MockClient
        - p *prompt.Prompter
        - w http.ResponseWriter
        - r *http.Request
    nolintlint:
      require-explanation: true
      require-specific: true
    dupl:
      threshold: 120
  exclusions:
    rules:
      # Test files can have unchecked errors
      - path: _test\.go
        linters:
          - errcheck
      # Test files use relaxed permissions and subprocess patterns
      - path: _test\.go
        linters:
          - gosec
      # Allow concise names in table-driven tests
      - path: _test\.go
        linters:
          - varnamelen
      # Allow explicit table-driven duplication in tests for clarity
      - path: _test\.go
        linters:
          - dupl

formatters:
  enable:
    - gofumpt         # Strict formatting
    - goimports       # Import management
  settings:
    gofumpt:
      extra-rules: true
