# GoReleaser configuration for Mush CLI
# Documentation: https://goreleaser.com

version: 2

project_name: mush

before:
  hooks:
    - go mod tidy

builds:
  - id: mush
    main: ./cmd/mush
    binary: mush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  github:
    owner: musher-dev
    name: mush
  draft: false
  mode: keep-existing
  prerelease: auto
  name_template: "Mush v{{.Version}}"
