name: Bug Report
description: Report a bug in Mush CLI
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Mush version
      description: Output of `mush version`
      placeholder: "mush v0.2.0 (abc1234)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x86_64)
        - Linux (arm64)
        - Windows (WSL)
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Run `mush link --habitat foo`
        2. Wait for a job to be claimed
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Paste output from running with `--verbose` flag.
      render: text
    validations:
      required: false

  - type: textarea
    id: doctor
    attributes:
      label: Doctor output
      description: Paste output of `mush doctor`.
      render: text
    validations:
      required: false
